/** Settings page tabs — privilege strings match Staff Management checkboxes. */
export const SETTINGS_CATEGORIES = [
  { id: "accounts", label: "Default accounts" },
  { id: "inventory", label: "Inventory & costing" },
  { id: "pricing", label: "Pricing & sales" },
  { id: "banking", label: "Banking & tax" },
  { id: "organization", label: "Organization" },
  { id: "store", label: "Online store & branding" },
  { id: "corrections", label: "Corrections & history" },
];

export const SETTINGS_TABS = [
  {
    value: "payable",
    label: "Payable",
    privilege: "Settings Payable",
    category: "accounts",
  },
  {
    value: "receivable",
    label: "Receivable",
    privilege: "Settings Receivable",
    category: "accounts",
  },
  {
    value: "cost-of-service",
    label: "Cost Of Service",
    privilege: "Settings Cost Of Service",
    category: "accounts",
  },
  {
    value: "sales-revenue",
    label: "Sales Revenue",
    privilege: "Settings Sales Revenue",
    category: "accounts",
  },
  {
    value: "work-in-progress",
    label: "Work in Progress",
    privilege: "Settings Work in Progress",
    category: "accounts",
  },
  {
    value: "finished-goods",
    label: "Finished Goods",
    privilege: "Settings Finished Goods",
    category: "accounts",
  },
  {
    value: "abnormal-loss",
    label: "Abnormal Loss",
    privilege: "Settings Abnormal Loss",
    category: "accounts",
  },
  {
    value: "scrap-inventory",
    label: "Scrap Inventory",
    privilege: "Settings Scrap Inventory",
    category: "accounts",
  },
  {
    value: "opening-balance-equity",
    label: "Opening Balance Equity",
    privilege: "Settings Opening Balance Equity",
    category: "accounts",
  },
  {
    value: "pro-bono",
    label: "Pro Bono",
    privilege: "Settings Pro Bono",
    category: "accounts",
  },
  {
    value: "depreciation-method",
    label: "Depreciation Method",
    privilege: "Settings Depreciation Method",
    altPrivileges: [
      "Settings Payable",
      "Settings Receivable",
      "Settings Cost Of Service",
      "Settings Sales Revenue",
      "Settings Work in Progress",
      "Settings Finished Goods",
      "Settings Abnormal Loss",
      "Settings Scrap Inventory",
      "Settings Opening Balance Equity",
      "Settings Pro Bono",
      "Settings Costing Method",
      "Settings",
    ],
    category: "accounts",
  },
  {
    value: "costing-method",
    label: "Costing Method",
    privilege: "Settings Costing Method",
    category: "inventory",
  },
  {
    value: "default-cost-valuation",
    label: "Default Cost / Valuation",
    privilege: "Settings Default Cost Valuation",
    category: "inventory",
  },
  {
    value: "inventory-valuation",
    label: "Inventory Valuation",
    privilege: "Settings Inventory Valuation",
    category: "inventory",
  },
  {
    value: "product-multiplier",
    label: "Product Multiplier",
    privilege: "Settings Product Multiplier",
    category: "inventory",
    requiresProcessCosting: true,
  },
  {
    value: "costing-template",
    label: "Costing Template",
    privilege: "Settings Costing Template",
    category: "inventory",
    requiresJobProductCosting: true,
  },
  {
    value: "production-correction",
    label: "Production Correction",
    privilege: "Settings Production Correction",
    category: "inventory",
    requiresManufacturing: true,
  },
  {
    value: "material-requisition",
    label: "Material Requisition",
    privilege: "Settings Material Requisition",
    category: "inventory",
    requiresManufacturing: true,
  },
  {
    value: "price-setup",
    label: "Price Set-up",
    privilege: "Settings Price Set-up",
    category: "pricing",
  },
  {
    value: "rate-setup",
    label: "Rate Setup",
    privilege: "Settings Rate Setup",
    category: "pricing",
  },
  {
    value: "discount-setup",
    label: "Discount Setup",
    privilege: "Settings Discount Setup",
    category: "pricing",
  },
  {
    value: "customer-types",
    label: "Customer Types",
    privilege: "Settings Customer Types",
    category: "pricing",
  },
  {
    value: "vat-policy",
    label: "VAT Policy",
    privilege: "Settings VAT Policy",
    category: "pricing",
  },
  {
    value: "invoice-closing",
    label: "Invoice Closing Time",
    privilege: "Settings Invoice Closing",
    altPrivileges: [
      "Settings VAT Policy",
      "Settings",
      "Settings Payable",
      "Settings Receivable",
    ],
    category: "pricing",
  },
  {
    value: "bank-setup",
    label: "Bank Setup",
    privilege: "Settings Bank Setup",
    category: "banking",
  },
  {
    value: "bank-list",
    label: "Bank List",
    privilege: "Settings Bank List",
    category: "banking",
  },
  {
    value: "tax-setup",
    label: "Tax Setup",
    privilege: "Settings Tax Setup",
    category: "banking",
  },
  {
    value: "paye-setup",
    label: "PAYE Setup",
    privilege: "Settings PAYE Setup",
    altPrivileges: ["Settings Tax Setup"],
    category: "banking",
  },
  {
    value: "departments",
    label: "Manage Departments",
    privilege: "Settings Manage Departments",
    category: "organization",
  },
  {
    value: "branches",
    label: "Manage Warehouses",
    privilege: "Settings Manage Branches",
    category: "organization",
  },
  {
    value: "team-setup",
    label: "Team Setup",
    privilege: "Settings Team Setup",
    category: "organization",
  },
  {
    value: "user-roles",
    label: "User Roles",
    privilege: "Settings User Roles",
    category: "organization",
  },
  {
    value: "online-ordering",
    label: "Online Ordering",
    privilege: "Settings Online Ordering",
    category: "store",
  },
  {
    value: "default-receipt",
    label: "Default Receipt",
    privilege: "Settings Default Receipt",
    category: "store",
  },
  {
    value: "marketplace",
    label: "Marketplace",
    privilege: "Settings Marketplace",
    category: "store",
  },
  {
    value: "branding",
    label: "Branding",
    privilege: "Settings Branding",
    category: "store",
  },
  {
    value: "header-settings",
    label: "Header Settings",
    privilege: "Settings Branding",
    altPrivileges: ["Settings Header", "Settings Header Settings"],
    category: "store",
  },
  {
    value: "invoice-correction",
    label: "Invoice Correction",
    privilege: "Settings Invoice Correction",
    category: "corrections",
  },
  {
    value: "journal-correction",
    label: "Journal Correction",
    privilege: "Settings Journal Correction",
    category: "corrections",
  },
  {
    value: "imprest-history",
    label: "Imprest History",
    privilege: "Settings Imprest History",
    category: "corrections",
  },
];

/** Legacy hash anchors → tab value (deep links from other pages). */
export const SETTINGS_HASH_TO_TAB = {
  "manage-departments": "departments",
  "manage-branches": "branches",
  "price-setup": "price-setup",
  "team-setup": "team-setup",
  "rate-setup": "rate-setup",
  "discount-setup": "discount-setup",
  "bank-setup": "bank-setup",
  "tax-setup": "tax-setup",
  "paye-setup": "paye-setup",
  "header-settings": "header-settings",
  "production-abnormal-loss-account": "abnormal-loss",
  "production-scrap-inventory-account": "scrap-inventory",
};
